### ISSUE TITLE
Divisions

### ISSUE THREAD

**Issue by jpincas** [dogpakk/roadmap#7]
- a simple way to separate out entities according to business 'divisions' or 'brands'
- tenants can create their own 'divisions'
- and then new field in ALL entities = `division` which is a choice from that list
- the entire admin panel would then have a single control somewhere, perhaps in the sidebar, that would allow you to switch to a 'division' (By default you'd be in 'all divisions' mode)
- when switching to a 'division' - all list filters would be appended with one to only return results from that 'division'

**Comment by jessipg** [comment]
Already implemented and released
